---
name: 'Dump GitHub context'
description: 'Dump GitHub context'
runs:
  using: "composite"
  steps:
    - name: 'Dump GitHub context'
      shell: bash
      run: echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: 'Dump environmental variables'
      shell: bash
      run: env | sort
