---
name: 'ci'

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - master
    tags:
      - latest
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: 'uat'
        options:
          - uat
          - stg
          - prd


concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  pre-commit:
    uses: ./.github/workflows/pre_commit.yml
    secrets: inherit

  tests:
    runs-on: ubuntu-latest
    needs: [pre-commit]
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      # composite actions
      - name: 'Dump context'
        uses: ./.github/actions/dump_context

  create-tag:
    runs-on: ubuntu-latest
    needs: [pre-commit]
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: 'Create tag: latest'
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "github-actions@github.com"
          remote="https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

          git tag $TAG --force

          git push "${remote}" $TAG --force
        env:
          TAG: "latest"
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          TOKEN: ${{ secrets.PAT }}
