---
name: "ci 2"

on:   # yamllint disable-line rule:truthy
  workflow_run:
    workflows: ["pre-commit"]
    types:
      - completed


concurrency:
  group: ci-dev-deploy-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


defaults:
  run:
    shell: bash

jobs:
  context-check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      # composite actions
      - name: 'Dump context'
        uses: ./.github/actions/dump_context
      - name: 'Dump ${{ github.event.workflow_run.html_url }}'
        run: |
          echo ${{ github.event.workflow_run.html_url }}
